### ISSUE TITLE
Signature generation

### ISSUE THREAD

**Issue by Tomatov** [Ygnecz/MTLic#1]
Hi Ygnecz, 
Can You write, how to create signature?

If we have Software ID AAAA-BBBB
then 

-- Software ID in Integer is
198695372904

-- LicVal [ 6 ]
b'h\xc8*C.\x00'

-- License level
1

-- LIC (MT Transform REV)
b'\xcd\x82\xb0\xef\xe0\xaf\x1b\xe3\x8d?\x967\xe5\xe2\x1b\xe8'

-- Hash( LicVal ) - SignatureVerification
bytearray(b'\xae\xcf\xce,\xf765\xdd\xfe\xc2\xe8\xa02\xd1D\x1e8\x95\rz\x13<\x9b\x00\x03\xcb\xa7\x18\xacL\xf4\xd3')

Now: do I need to modify license hash or not? 
How? 

I think i am able to compute Elliptic Curve (Y) but there I need **signature** * **PubKey** * **hash** + **G**. 

Only for education purposes, x86 is legacy mode, this generation will not work with CHR. 
Please explain me steps. Thank You!

**Comment by Ygnecz** [comment]
Not possible to generate valid signature without ECC private key.
