### ISSUE TITLE
How to get the ECC Key Private?

### ISSUE THREAD

**Issue by GuckTubeYT** [Ygnecz/MTLic#4]
Do you know how to get the ECC Key Private?

**Comment by Chupaka** [comment]
Ask Mikrotik. Anyone with Private key can generate/sell valid licenses. Are you sure it's easily obtainable?

**Comment by GuckTubeYT** [comment]
> Ask Mikrotik. Anyone with Private key can generate/sell valid licenses. Are you sure it's easily obtainable?

its very hard 😅
